USE BASEDATOS
GO

IF OBJECT_ID('[dbo].[spConKernelIDE]','P') IS NOT NULL
BEGIN
	DROP PROCEDURE spConKernelIDE
END
GO
--EXEC spConKernelIDE

CREATE PROCEDURE spConKernelIDE

AS


--COUNTS DE REGLAS ACTIVAS Y DESACTIVADAS PARA EL ITEM 526    
SELECT     
 COUNT( CASE WHEN fiSubItemStat = 1 THEN 1 END ) AS Activas,    
 COUNT( CASE WHEN fiSubItemStat = 0 THEN 1 END ) AS Desactivadas    
FROM CatGDIDesTec WITH(NOLOCK)    
WHERE fiItemId = 526    
    
--COUNTS DE REGLAS ACTIVAS Y DESACTIVADAS PARA EL ITEM 100    
SELECT     
 COUNT( CASE WHEN fiSubItemStat = 1 THEN 1 END ) AS Activas,    
 COUNT( CASE WHEN fiSubItemStat = 0 THEN 1 END ) AS Desactivadas    
FROM CatGDIDesTec WITH(NOLOCK)    
WHERE fiItemId = 100    
    
--CONSULTA DE LOS ITEMS 526    
SELECT * FROM CATGDIDESTEC WITH(NOLOCK) WHERE FIITEMID = 526    
    
--CONSULTA DE LOS ITEMS 100    
SELECT * FROM CatGDIDesTec WITH(NOLOCK) WHERE fiItemId = 100


--OBTENER EL ULTIMO SUBITEMID DE CATGDIDESTEC ITEMID 526
SELECT MAX(fiSubItemId) MAX526 FROM CatGDIDesTec WITH(NOLOCK) WHERE fiItemId = 526

--OBTENER EL ULTIMO SUBITEMID DE CATGDIDESTEC ITEMID 100
SELECT MAX(fiSubItemId) MAX100 FROM CatGDIDesTec WITH(NOLOCK) WHERE fiItemId = 100